---
apache_enabled: true
apache_autostart: false
apache_conf_items:
  - regexp: "^#?ServerName .*"
    line: "ServerName localhost:{{ apache_listen_port }}"
  - regexp: "^DocumentRoot .*"
    line: 'DocumentRoot "{{ apache_documentroot }}"'
  - regexp: '^<Directory "((?!cgi).)*">'
    line: '<Directory "{{ apache_documentroot }}">'
  - regexp: "^ErrorLog .*"
    line: "ErrorLog |/usr/bin/cat"
  - regexp: "^    CustomLog .*"
    line: "    CustomLog |/usr/bin/cat combined"
  - regexp: '^    #\n    AllowOverride .*'
    line: '    #\n    AllowOverride All'
